### ISSUE TITLE
Ruby 3.2.0 - LoadError: cannot load such file -- rbsecp256k1/rbsecp256k1

### ISSUE THREAD

**Issue by schinery** [etscrivner/rbsecp256k1#61]
In the process of upgrading an app to Ruby 3.2.0 and am getting this error on the CI for code that previously worked in Ruby 3.1.3.

```sh
rails aborted!
LoadError: cannot load such file -- rbsecp256k1/rbsecp256k1
/home/circleci/my-app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.2.0/gems/rbsecp256k1-5.1.0/lib/rbsecp256k1.rb:10:in `<main>'
```

Looking in to `lib/rbsecp256k1.rb` it has `require 'rbsecp256k1/rbsecp256k1'` but there is no file there of that name, just a folder, so can this be removed?

**Comment by schinery** [comment]
Had a go at removing it in https://github.com/etscrivner/rbsecp256k1/pull/62

**Comment by etscrivner** [comment]
@schinery Going to do some local debugging against Ruby 3.2.0 and see if I can find the source of the issue.

**Comment by schinery** [comment]
@etscrivner am also wondering if this issue is more bundler related too, which got bumped to 2.4.1 🤷🏻‍♂️

**Comment by etscrivner** [comment]
@schinery I'm going to do a full dependency update here including bundler.

**Comment by etscrivner** [comment]
@schinery This has been fixed in #66 and a new version (v5.1.1) has been pushed to rubygems.org. Please let me know if this fixes your issue.

**Comment by schinery** [comment]
@etscrivner will check tomorrow and let you know 👍🏻

**Comment by schinery** [comment]
@etscrivner all is good, am no longer getting the error with the 5.1.1 release. 

Thanks for prompt fix 🙏🏻
